### PR TITLE
Update italian translation

### PR DESCRIPTION
**Pull request by Gringit**
by Gringo

### CODE REVIEW

**Comment by persianpros** [comment]
Thanks but what has been updated?

**Comment by Gringit** [comment]
Just cleanup and add some rows in the translation team reference.

**Comment by persianpros** [comment]
But I can't see the changes ...

**Comment by Gringit** [comment]
First 5 rows of the file...

**Comment by persianpros** [comment]
I mean those are just comment lines so they won't do anything ...

**Pull request closed without merging**
